version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver # Ensure SQL Server container is started first
